### ISSUE TITLE
Default config contains pre python hook, which is always printed

### ISSUE THREAD

**Issue by Profpatsch** [ad-si/TaskLite#26]
The default configuration contains the section

```
hooks:
  #| Is per default the "hooks" directory in the `dataDir`
  # directory: /custom/path/hooks
  launch:
    pre:
      - interpreter: python3
        body: print('Python test')
```

which will lead an “unconfigured” tasklite to always print `Python test` when you call it.
